class SurahInfo {
  final int number;
  final String name;
  final String englishName;
  final String englishNameTranslation;
  final int numberOfAyahs;
  final int startOnPage;
  final String revelationType;

  const SurahInfo({
    required this.number,
    required this.name,
    required this.englishName,
    required this.englishNameTranslation,
    required this.numberOfAyahs,
    required this.startOnPage,
    required this.revelationType,
  });
}

const List<SurahInfo> quranSurahs = [
  SurahInfo(
    number: 1,
    name: "الفاتحة",
    englishName: "Al-Fatiha",
    englishNameTranslation: "The Opening",
    numberOfAyahs: 7,
    startOnPage: 1,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 2,
    name: "البقرة",
    englishName: "Al-Baqarah",
    englishNameTranslation: "The Cow",
    numberOfAyahs: 286,
    startOnPage: 2,
    revelationType: "Medinan",
  ),
  SurahInfo(
    number: 3,
    name: "آل عمران",
    englishName: "Aal-Imran",
    englishNameTranslation: "The Family of Imran",
    numberOfAyahs: 200,
    startOnPage: 50,
    revelationType: "Medinan",
  ),
  SurahInfo(
    number: 4,
    name: "النساء",
    englishName: "An-Nisa",
    englishNameTranslation: "The Women",
    numberOfAyahs: 176,
    startOnPage: 77,
    revelationType: "Medinan",
  ),
  SurahInfo(
    number: 5,
    name: "المائدة",
    englishName: "Al-Ma'idah",
    englishNameTranslation: "The Table Spread",
    numberOfAyahs: 120,
    startOnPage: 106,
    revelationType: "Medinan",
  ),
  SurahInfo(
    number: 6,
    name: "الأنعام",
    englishName: "Al-An'am",
    englishNameTranslation: "The Cattle",
    numberOfAyahs: 165,
    startOnPage: 128,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 7,
    name: "الأعراف",
    englishName: "Al-A'raf",
    englishNameTranslation: "The Heights",
    numberOfAyahs: 206,
    startOnPage: 151,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 8,
    name: "الأنفال",
    englishName: "Al-Anfal",
    englishNameTranslation: "The Spoils of War",
    numberOfAyahs: 75,
    startOnPage: 177,
    revelationType: "Medinan",
  ),
  SurahInfo(
    number: 9,
    name: "التوبة",
    englishName: "At-Tawbah",
    englishNameTranslation: "The Repentance",
    numberOfAyahs: 129,
    startOnPage: 187,
    revelationType: "Medinan",
  ),
  SurahInfo(
    number: 10,
    name: "يونس",
    englishName: "Yunus",
    englishNameTranslation: "Jonah",
    numberOfAyahs: 109,
    startOnPage: 208,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 11,
    name: "هود",
    englishName: "Hud",
    englishNameTranslation: "Hud",
    numberOfAyahs: 123,
    startOnPage: 221,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 12,
    name: "يوسف",
    englishName: "Yusuf",
    englishNameTranslation: "Joseph",
    numberOfAyahs: 111,
    startOnPage: 235,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 13,
    name: "الرعد",
    englishName: "Ar-Ra'd",
    englishNameTranslation: "The Thunder",
    numberOfAyahs: 43,
    startOnPage: 249,
    revelationType: "Medinan",
  ),
  SurahInfo(
    number: 14,
    name: "إبراهيم",
    englishName: "Ibrahim",
    englishNameTranslation: "Abraham",
    numberOfAyahs: 52,
    startOnPage: 255,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 15,
    name: "الحجر",
    englishName: "Al-Hijr",
    englishNameTranslation: "The Rocky Tract",
    numberOfAyahs: 99,
    startOnPage: 262,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 16,
    name: "النحل",
    englishName: "An-Nahl",
    englishNameTranslation: "The Bee",
    numberOfAyahs: 128,
    startOnPage: 267,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 17,
    name: "الإسراء",
    englishName: "Al-Isra",
    englishNameTranslation: "The Night Journey",
    numberOfAyahs: 111,
    startOnPage: 282,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 18,
    name: "الكهف",
    englishName: "Al-Kahf",
    englishNameTranslation: "The Cave",
    numberOfAyahs: 110,
    startOnPage: 293,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 19,
    name: "مريم",
    englishName: "Maryam",
    englishNameTranslation: "Mary",
    numberOfAyahs: 98,
    startOnPage: 305,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 20,
    name: "طه",
    englishName: "Ta-Ha",
    englishNameTranslation: "Ta-Ha",
    numberOfAyahs: 135,
    startOnPage: 312,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 21,
    name: "الأنبياء",
    englishName: "Al-Anbiya",
    englishNameTranslation: "The Prophets",
    numberOfAyahs: 112,
    startOnPage: 322,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 22,
    name: "الحج",
    englishName: "Al-Hajj",
    englishNameTranslation: "The Pilgrimage",
    numberOfAyahs: 78,
    startOnPage: 332,
    revelationType: "Medinan",
  ),
  SurahInfo(
    number: 23,
    name: "المؤمنون",
    englishName: "Al-Mu'minun",
    englishNameTranslation: "The Believers",
    numberOfAyahs: 118,
    startOnPage: 342,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 24,
    name: "النور",
    englishName: "An-Nur",
    englishNameTranslation: "The Light",
    numberOfAyahs: 64,
    startOnPage: 350,
    revelationType: "Medinan",
  ),
  SurahInfo(
    number: 25,
    name: "الفرقان",
    englishName: "Al-Furqan",
    englishNameTranslation: "The Criterion",
    numberOfAyahs: 77,
    startOnPage: 359,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 26,
    name: "الشعراء",
    englishName: "Ash-Shu'ara",
    englishNameTranslation: "The Poets",
    numberOfAyahs: 227,
    startOnPage: 367,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 27,
    name: "النمل",
    englishName: "An-Naml",
    englishNameTranslation: "The Ant",
    numberOfAyahs: 93,
    startOnPage: 377,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 28,
    name: "القصص",
    englishName: "Al-Qasas",
    englishNameTranslation: "The Stories",
    numberOfAyahs: 88,
    startOnPage: 385,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 29,
    name: "العنكبوت",
    englishName: "Al-Ankabut",
    englishNameTranslation: "The Spider",
    numberOfAyahs: 69,
    startOnPage: 396,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 30,
    name: "الروم",
    englishName: "Ar-Rum",
    englishNameTranslation: "The Romans",
    numberOfAyahs: 60,
    startOnPage: 404,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 31,
    name: "لقمان",
    englishName: "Luqman",
    englishNameTranslation: "Luqman",
    numberOfAyahs: 34,
    startOnPage: 411,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 32,
    name: "السجدة",
    englishName: "As-Sajdah",
    englishNameTranslation: "The Prostration",
    numberOfAyahs: 30,
    startOnPage: 415,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 33,
    name: "الأحزاب",
    englishName: "Al-Ahzab",
    englishNameTranslation: "The Confederates",
    numberOfAyahs: 73,
    startOnPage: 418,
    revelationType: "Medinan",
  ),
  SurahInfo(
    number: 34,
    name: "سبأ",
    englishName: "Saba",
    englishNameTranslation: "Sheba",
    numberOfAyahs: 54,
    startOnPage: 428,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 35,
    name: "فاطر",
    englishName: "Fatir",
    englishNameTranslation: "The Originator",
    numberOfAyahs: 45,
    startOnPage: 434,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 36,
    name: "يس",
    englishName: "Ya-Sin",
    englishNameTranslation: "Ya-Sin",
    numberOfAyahs: 83,
    startOnPage: 440,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 37,
    name: "الصافات",
    englishName: "As-Saffat",
    englishNameTranslation: "Those who set ranks",
    numberOfAyahs: 182,
    startOnPage: 446,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 38,
    name: "ص",
    englishName: "Sad",
    englishNameTranslation: "The letter Sad",
    numberOfAyahs: 88,
    startOnPage: 453,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 39,
    name: "الزمر",
    englishName: "Az-Zumar",
    englishNameTranslation: "The Troops",
    numberOfAyahs: 75,
    startOnPage: 458,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 40,
    name: "غافر",
    englishName: "Ghafir",
    englishNameTranslation: "The Forgiver",
    numberOfAyahs: 85,
    startOnPage: 467,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 41,
    name: "فصلت",
    englishName: "Fussilat",
    englishNameTranslation: "Explained in Detail",
    numberOfAyahs: 54,
    startOnPage: 477,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 42,
    name: "الشورى",
    englishName: "Ash-Shura",
    englishNameTranslation: "Consultation",
    numberOfAyahs: 53,
    startOnPage: 483,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 43,
    name: "الزخرف",
    englishName: "Az-Zukhruf",
    englishNameTranslation: "Ornaments of Gold",
    numberOfAyahs: 89,
    startOnPage: 489,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 44,
    name: "الدخان",
    englishName: "Ad-Dukhan",
    englishNameTranslation: "The Smoke",
    numberOfAyahs: 59,
    startOnPage: 496,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 45,
    name: "الجاثية",
    englishName: "Al-Jathiyah",
    englishNameTranslation: "Crouching",
    numberOfAyahs: 37,
    startOnPage: 499,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 46,
    name: "الأحقاف",
    englishName: "Al-Ahqaf",
    englishNameTranslation: "The Wind-Curved Sandhills",
    numberOfAyahs: 35,
    startOnPage: 502,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 47,
    name: "محمد",
    englishName: "Muhammad",
    englishNameTranslation: "Muhammad",
    numberOfAyahs: 38,
    startOnPage: 507,
    revelationType: "Medinan",
  ),
  SurahInfo(
    number: 48,
    name: "الفتح",
    englishName: "Al-Fath",
    englishNameTranslation: "The Victory",
    numberOfAyahs: 29,
    startOnPage: 511,
    revelationType: "Medinan",
  ),
  SurahInfo(
    number: 49,
    name: "الحجرات",
    englishName: "Al-Hujurat",
    englishNameTranslation: "The Dwellings",
    numberOfAyahs: 18,
    startOnPage: 515,
    revelationType: "Medinan",
  ),
  SurahInfo(
    number: 50,
    name: "ق",
    englishName: "Qaf",
    englishNameTranslation: "The Letter Qaf",
    numberOfAyahs: 45,
    startOnPage: 518,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 51,
    name: "الذاريات",
    englishName: "Adh-Dhariyat",
    englishNameTranslation: "The Winnowing Winds",
    numberOfAyahs: 60,
    startOnPage: 520,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 52,
    name: "الطور",
    englishName: "At-Tur",
    englishNameTranslation: "The Mount",
    numberOfAyahs: 49,
    startOnPage: 523,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 53,
    name: "النجم",
    englishName: "An-Najm",
    englishNameTranslation: "The Star",
    numberOfAyahs: 62,
    startOnPage: 526,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 54,
    name: "القمر",
    englishName: "Al-Qamar",
    englishNameTranslation: "The Moon",
    numberOfAyahs: 55,
    startOnPage: 528,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 55,
    name: "الرحمن",
    englishName: "Ar-Rahman",
    englishNameTranslation: "The Beneficent",
    numberOfAyahs: 78,
    startOnPage: 531,
    revelationType: "Medinan",
  ),
  SurahInfo(
    number: 56,
    name: "الواقعة",
    englishName: "Al-Waqi'ah",
    englishNameTranslation: "The Event",
    numberOfAyahs: 96,
    startOnPage: 534,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 57,
    name: "الحديد",
    englishName: "Al-Hadid",
    englishNameTranslation: "The Iron",
    numberOfAyahs: 29,
    startOnPage: 537,
    revelationType: "Medinan",
  ),
  SurahInfo(
    number: 58,
    name: "المجادلة",
    englishName: "Al-Mujadilah",
    englishNameTranslation: "The Pleading Woman",
    numberOfAyahs: 22,
    startOnPage: 542,
    revelationType: "Medinan",
  ),
  SurahInfo(
    number: 59,
    name: "الحشر",
    englishName: "Al-Hashr",
    englishNameTranslation: "The Exile",
    numberOfAyahs: 24,
    startOnPage: 545,
    revelationType: "Medinan",
  ),
  SurahInfo(
    number: 60,
    name: "الممتحنة",
    englishName: "Al-Mumtahanah",
    englishNameTranslation: "She that is to be examined",
    numberOfAyahs: 13,
    startOnPage: 549,
    revelationType: "Medinan",
  ),
  SurahInfo(
    number: 61,
    name: "الصف",
    englishName: "As-Saff",
    englishNameTranslation: "The Ranks",
    numberOfAyahs: 14,
    startOnPage: 551,
    revelationType: "Medinan",
  ),
  SurahInfo(
    number: 62,
    name: "الجمعة",
    englishName: "Al-Jumu'ah",
    englishNameTranslation: "The Congregation, Friday",
    numberOfAyahs: 11,
    startOnPage: 553,
    revelationType: "Medinan",
  ),
  SurahInfo(
    number: 63,
    name: "المنافقون",
    englishName: "Al-Munafiqun",
    englishNameTranslation: "The Hypocrites",
    numberOfAyahs: 11,
    startOnPage: 554,
    revelationType: "Medinan",
  ),
  SurahInfo(
    number: 64,
    name: "التغابن",
    englishName: "At-Taghabun",
    englishNameTranslation: "Mutual Disillusion",
    numberOfAyahs: 18,
    startOnPage: 556,
    revelationType: "Medinan",
  ),
  SurahInfo(
    number: 65,
    name: "الطلاق",
    englishName: "At-Talaq",
    englishNameTranslation: "The Divorce",
    numberOfAyahs: 12,
    startOnPage: 558,
    revelationType: "Medinan",
  ),
  SurahInfo(
    number: 66,
    name: "التحريم",
    englishName: "At-Tahrim",
    englishNameTranslation: "The Prohibition",
    numberOfAyahs: 12,
    startOnPage: 560,
    revelationType: "Medinan",
  ),
  SurahInfo(
    number: 67,
    name: "الملك",
    englishName: "Al-Mulk",
    englishNameTranslation: "The Sovereignty",
    numberOfAyahs: 30,
    startOnPage: 562,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 68,
    name: "القلم",
    englishName: "Al-Qalam",
    englishNameTranslation: "The Pen",
    numberOfAyahs: 52,
    startOnPage: 564,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 69,
    name: "الحاقة",
    englishName: "Al-Haqqah",
    englishNameTranslation: "The Reality",
    numberOfAyahs: 52,
    startOnPage: 566,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 70,
    name: "المعارج",
    englishName: "Al-Ma'arij",
    englishNameTranslation: "The Ascending Stairways",
    numberOfAyahs: 44,
    startOnPage: 568,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 71,
    name: "نوح",
    englishName: "Nuh",
    englishNameTranslation: "Noah",
    numberOfAyahs: 28,
    startOnPage: 570,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 72,
    name: "الجن",
    englishName: "Al-Jinn",
    englishNameTranslation: "The Jinn",
    numberOfAyahs: 28,
    startOnPage: 572,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 73,
    name: "المزمل",
    englishName: "Al-Muzzammil",
    englishNameTranslation: "The Enshrouded One",
    numberOfAyahs: 20,
    startOnPage: 574,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 74,
    name: "المدثر",
    englishName: "Al-Muddaththir",
    englishNameTranslation: "The Cloaked One",
    numberOfAyahs: 56,
    startOnPage: 575,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 75,
    name: "القيامة",
    englishName: "Al-Qiyamah",
    englishNameTranslation: "The Resurrection",
    numberOfAyahs: 40,
    startOnPage: 577,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 76,
    name: "الإنسان",
    englishName: "Al-Insan",
    englishNameTranslation: "The Man",
    numberOfAyahs: 31,
    startOnPage: 578,
    revelationType: "Medinan",
  ),
  SurahInfo(
    number: 77,
    name: "المرسلات",
    englishName: "Al-Mursalat",
    englishNameTranslation: "The Emissaries",
    numberOfAyahs: 50,
    startOnPage: 580,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 78,
    name: "النبأ",
    englishName: "An-Naba",
    englishNameTranslation: "The Tidings",
    numberOfAyahs: 40,
    startOnPage: 582,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 79,
    name: "النازعات",
    englishName: "An-Nazi'at",
    englishNameTranslation: "Those who drag forth",
    numberOfAyahs: 46,
    startOnPage: 583,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 80,
    name: "عبس",
    englishName: "Abasa",
    englishNameTranslation: "He Frowned",
    numberOfAyahs: 42,
    startOnPage: 585,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 81,
    name: "التكوير",
    englishName: "At-Takwir",
    englishNameTranslation: "The Overthrowing",
    numberOfAyahs: 29,
    startOnPage: 586,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 82,
    name: "الإنفطار",
    englishName: "Al-Infitar",
    englishNameTranslation: "The Cleaving",
    numberOfAyahs: 19,
    startOnPage: 587,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 83,
    name: "المطففين",
    englishName: "Al-Mutaffifin",
    englishNameTranslation: "The Defrauding",
    numberOfAyahs: 36,
    startOnPage: 587,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 84,
    name: "الانشقاق",
    englishName: "Al-Inshiqaq",
    englishNameTranslation: "The Rending Asunder",
    numberOfAyahs: 25,
    startOnPage: 589,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 85,
    name: "البروج",
    englishName: "Al-Buruj",
    englishNameTranslation: "The Mansions of the Stars",
    numberOfAyahs: 22,
    startOnPage: 590,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 86,
    name: "الطارق",
    englishName: "At-Tariq",
    englishNameTranslation: "The Nightcomer",
    numberOfAyahs: 17,
    startOnPage: 591,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 87,
    name: "الأعلى",
    englishName: "Al-A'la",
    englishNameTranslation: "The Most High",
    numberOfAyahs: 19,
    startOnPage: 591,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 88,
    name: "الغاشية",
    englishName: "Al-Ghashiyah",
    englishNameTranslation: "The Overwhelming Event",
    numberOfAyahs: 26,
    startOnPage: 592,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 89,
    name: "الفجر",
    englishName: "Al-Fajr",
    englishNameTranslation: "The Dawn",
    numberOfAyahs: 30,
    startOnPage: 593,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 90,
    name: "البلد",
    englishName: "Al-Balad",
    englishNameTranslation: "The City",
    numberOfAyahs: 20,
    startOnPage: 594,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 91,
    name: "الشمس",
    englishName: "Ash-Shams",
    englishNameTranslation: "The Sun",
    numberOfAyahs: 15,
    startOnPage: 595,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 92,
    name: "الليل",
    englishName: "Al-Layl",
    englishNameTranslation: "The Night",
    numberOfAyahs: 21,
    startOnPage: 595,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 93,
    name: "الضحى",
    englishName: "Ad-Duha",
    englishNameTranslation: "The Morning Hours",
    numberOfAyahs: 11,
    startOnPage: 596,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 94,
    name: "الشرح",
    englishName: "Ash-Sharh",
    englishNameTranslation: "The Relief",
    numberOfAyahs: 8,
    startOnPage: 596,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 95,
    name: "التين",
    englishName: "At-Tin",
    englishNameTranslation: "The Fig",
    numberOfAyahs: 8,
    startOnPage: 597,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 96,
    name: "العلق",
    englishName: "Al-Alaq",
    englishNameTranslation: "The Clot",
    numberOfAyahs: 19,
    startOnPage: 597,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 97,
    name: "القدر",
    englishName: "Al-Qadr",
    englishNameTranslation: "The Power",
    numberOfAyahs: 5,
    startOnPage: 598,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 98,
    name: "البينة",
    englishName: "Al-Bayyinah",
    englishNameTranslation: "The Clear Proof",
    numberOfAyahs: 8,
    startOnPage: 598,
    revelationType: "Medinan",
  ),
  SurahInfo(
    number: 99,
    name: "الزلزلة",
    englishName: "Az-Zalzalah",
    englishNameTranslation: "The Earthquake",
    numberOfAyahs: 8,
    startOnPage: 599,
    revelationType: "Medinan",
  ),
  SurahInfo(
    number: 100,
    name: "العاديات",
    englishName: "Al-Adiyat",
    englishNameTranslation: "The Coursers",
    numberOfAyahs: 11,
    startOnPage: 599,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 101,
    name: "القارعة",
    englishName: "Al-Qari'ah",
    englishNameTranslation: "The Calamity",
    numberOfAyahs: 11,
    startOnPage: 600,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 102,
    name: "التكاثر",
    englishName: "At-Takathur",
    englishNameTranslation: "Rivalry in Worldly Increase",
    numberOfAyahs: 8,
    startOnPage: 600,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 103,
    name: "العصر",
    englishName: "Al-Asr",
    englishNameTranslation: "The Declining Day",
    numberOfAyahs: 3,
    startOnPage: 601,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 104,
    name: "الهمزة",
    englishName: "Al-Humazah",
    englishNameTranslation: "The Slanderer",
    numberOfAyahs: 9,
    startOnPage: 601,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 105,
    name: "الفيل",
    englishName: "Al-Fil",
    englishNameTranslation: "The Elephant",
    numberOfAyahs: 5,
    startOnPage: 601,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 106,
    name: "قريش",
    englishName: "Quraish",
    englishNameTranslation: "Quraish",
    numberOfAyahs: 4,
    startOnPage: 602,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 107,
    name: "الماعون",
    englishName: "Al-Ma'un",
    englishNameTranslation: "The Small Kindnesses",
    numberOfAyahs: 7,
    startOnPage: 602,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 108,
    name: "الكوثر",
    englishName: "Al-Kawthar",
    englishNameTranslation: "Abundance",
    numberOfAyahs: 3,
    startOnPage: 603,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 109,
    name: "الكافرون",
    englishName: "Al-Kafirun",
    englishNameTranslation: "The Disbelievers",
    numberOfAyahs: 6,
    startOnPage: 603,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 110,
    name: "النصر",
    englishName: "An-Nasr",
    englishNameTranslation: "The Divine Support",
    numberOfAyahs: 3,
    startOnPage: 603,
    revelationType: "Medinan",
  ),
  SurahInfo(
    number: 111,
    name: "المسد",
    englishName: "Al-Masad",
    englishNameTranslation: "The Palm Fibre",
    numberOfAyahs: 5,
    startOnPage: 603,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 112,
    name: "الإخلاص",
    englishName: "Al-Ikhlas",
    englishNameTranslation: "The Sincerity",
    numberOfAyahs: 4,
    startOnPage: 604,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 113,
    name: "الفلق",
    englishName: "Al-Falaq",
    englishNameTranslation: "The Daybreak",
    numberOfAyahs: 5,
    startOnPage: 604,
    revelationType: "Meccan",
  ),
  SurahInfo(
    number: 114,
    name: "الناس",
    englishName: "An-Nas",
    englishNameTranslation: "Mankind",
    numberOfAyahs: 6,
    startOnPage: 604,
    revelationType: "Meccan",
  ),
];
